import Nav from "../../components/navigationbar/bottomNav.jsx";
import { BsGraphUpArrow } from "react-icons/bs";
import { MdFavorite } from "react-icons/md";
import { FaSackDollar, FaMagnifyingGlassDollar } from "react-icons/fa6";
import { FaPiggyBank } from "react-icons/fa";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NavLayout({ children }) {
  const menuItems = [
    { title: "홈", icon: <FaPiggyBank />, path: "home" },
    { title: "현재가", icon: <BsGraphUpArrow />, path: "quotes" },
    { title: "선택종목", icon: <MdFavorite />, path: "favorite" },
    { title: "보유종목", icon: <FaSackDollar />, path: "stocks" },
    { title: "검색", icon: <FaMagnifyingGlassDollar />, path: "search" },
  ]

  return (
    <>
      <div className="w-[36rem] h-[calc(100%-4rem)] bg-white">
        {children}
      </div>
      <Nav menuItems={menuItems} />
    </>
  );
}
