import Nav from "../../components/navigationbar/bottomNav.jsx";
import { MdHome } from "react-icons/md";
import { FaCreditCard, FaChartLine } from "react-icons/fa";
import { GiHamburgerMenu } from "react-icons/gi";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NavLayout({ children }) {
  const menuItems = [
    {title: "홈", icon: <MdHome />, path: "home"},
    {title: "나의카드", icon: <FaCreditCard />, path: "my-card"},
    {title: "투자", icon: <FaChartLine />, path: "piece-stock/home"},
    {title: "전체", icon: <GiHamburgerMenu />, path: ""},
  ]

  return (
    <>
      <div className={`h-full overflow-scroll bg-slate-50 [&::-webkit-scrollbar]:hidden`}
        style={{
          scrollbarWidth: 'none',
          msOverflowStyle: 'none',
        }}>
        {children}
      </div>
      <Nav menuItems={menuItems} />
    </>
  );
}
