const Franchises = {
    group2: '/franchises/2개.png',
    group3: '/franchises/3개.png',
    group4: '/franchises/4개.png',
    cu: '/franchises/cu.png',
    gs: '/franchises/gs칼텍스.png',
    kt: '/franchises/kt.png',
    sk: '/franchises/sk텔레콤.png',
    netflix: '/franchises/넷플릭스.png',
    hd: '/franchises/더현대.png',
    lotte: '/franchises/롯데시네마.png',
    musinsa: '/franchises/무신사.png',
    millie: '/franchises/밀리의서재.png',
    baemin: '/franchises/배달의민족.png',
    starbucks: '/franchises/스타벅스.png',
    socar: '/franchises/쏘카.png',
    yanolja: '/franchises/야놀자.png',
    airbnb: '/franchises/에어비엔비.png',
    ably: '/franchises/에이블리.png',
    emart: '/franchises/이마트.png',
    interparktour: '/franchises/인터파크투어.png',
    kakaotaxi: '/franchises/카카오택시.png',
    twosomeplace: '/franchises/투썸플레이스.png',
    tving: '/franchises/티빙.png'
};
export default Franchises;