import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="flex justify-center h-full">
      <body
        className={`flex flex-col w-96 h-full bg-slate-400`}
      >
        {children}
      </body>
    </html>
  );
}
