import "./globals.css";
import {SessionProvider} from "next-auth/react"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionProvider>
      <html lang="en" className="flex justify-center h-full">
        <body
          className={`flex flex-col w-[36rem] h-full bg-slate-400`}
          >
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
