import "./globals.css";
import { SessionProvider } from "next-auth/react"

export const metadata = {
  title: "Quostomize",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=1"
};

export default function RootLayout({ children }) {
  return (
    <SessionProvider>
      <html lang="en" className="flex justify-center h-full overflow-hidden">
        <body
          className={`flex flex-col w-full h-full bg-slate-400`}
          >
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
